### ISSUE TITLE
Physical size of images

### ISSUE THREAD

**Issue by smistad** [UnityImaging/scantensus-echo#2]
Hi

In order to reproduce your results on automatic measurements of wall thickness and LV diameters we need to know the physical size of the images.
So that we can go from measurements in pixel units to physical units (mm, cm).
I am not able to find this information anywhere in the dataset.

Best regards,
Erik Smistad

**Comment by Doul00** [comment]
I am facing the same issue. Would it be possible to get this information @mshunshin ?

**Comment by mshunshin** [comment]
Hi,

I have had a few requests for this data - so it has been uploaded to the website.

Please find it at https://data.unityimaging.net/additional.html (where you will find data from other requests).

I am always happy to here from users of the data to chat about AI / collaborate - so feel free to drop me an email.

Hope that helps.

Matt
